sudo: false
language: generic

env:
  global:
      # HACKAGE_PASSWORD
    - secure: "bVtV8gJZ+s08cF7ONOUZ2ZDNfaDNCYVWTmuKthaKjBZOqSZM8SFtZFaczcvd25uGKmVg4z6V7EAoNmEGdLka/9ouySndXMlCECOn+WEX2v4YHWL7KiIxncKIpFeOGUygFqI2veDbxrQFR4YY+pGXlSuqQdfYgQq/OFpt9PzwXPS8malfOBVEtKJ9Su9vmANWUywGQbfb6/YcfHLFiLJdya9rcWDZsz+jJHr8BVY9w6pAhYPwQnovP1FUClPLHKAGVwshtkb/kFiI/zq9kAK5w57AAD/EIWLcBChcu93m5/1ROhSMosCGWl2Hq5CrNK81hRS8kTrMQG5UMRlkutdbaCNW+77Xz4avo8GOVCys7tNSr59pcXTsFEVH5VYKiWQFRoIjCJ52nkXClD3RTCNmp8u/yeogzjPtVZGJaMMNKEq2UFikWCFp/qQUAaxmuX/NIwECRGonN69TQvy59OI0v8D+/dt7kFYRO2k4wR3rcQ8P/MFWxmTH2d/UagBfbH10bSsiV/PY1WGf5AI7/s0VWYW8roa4fM+oXhEPcrPwFl2QAEWLXEnx4MbARIw9LdG2Flhvi6L68HlLzSrNF+69xMu6Pcc4voyRdpNiuiIlorloyEvkWSOFt5MHmlhiUL6LNqsrrER3sUxln0QKt1BSWRBNSBkghcBZ0RkfrqjfI9g="

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

install:
  - stack build --test --bench --only-dependencies

script:
  - stack test --pedantic

jobs:
  include:
    - stage: Hackage deploy
      # n is for "store credentials" question
      script: echo -e "AlexKane\n${HACKAGE_PASSWORD}\nn" | stack upload --pvp-bounds both .
      if: tag IS present
