sudo: false
language: generic

env:
  global:
      # HACKAGE_PASSWORD
    - secure: "hNDw+Dx05r6+q9YxH803EKH7frFu2aAW5WBWPoE++QcVsnRzUw1RieiDx0O/fBMSK8xSAJ55GaEqvpfIUIUWy4kJ1856f9NtdyEcXcuj9gg+cCS9srF50ZwikXjUqFzssCTjmxKxzsl4RzJE6TknKob0qKbHx6MfkFDBOrF2ZpTuTs3h3j9PJ0EaEeJw7a6ZKEhB5WtVwN92pV668gigQ4dwxK4s6FbCRtyD1vHSwOcP4NvZI/tjc7FoNoimZFOkc/AzevnsE8q6LuHLBHynlnT538i7jHPlp2g5dziyfmpaubMhguuvKCwqjzU5FAv+rAKqB89x6jsO5JJ2BA68KOf19N5O8EtlV5g9p/BqZ/dcUcMFRKNbVTemBW8C1vQDzhV8Q9dvMvciTHy3sVlvMcrTKdiTxkn2jwdZxDprRtVL0cPNr+eI51Xtcd6UEHbcP97egH1sFuQX4MYyZmwFicN68SWEJhgYeIHlYLF81HVnC3nYPPAwTCgCph/hC4MU4pTdeYhXILZAHa/u5pDQ0JJeSOWMYJ39nTIHzg9YSXFfWj4ELENBovoJK8qUnyyh4im5Ky7Eo7A4D2cT86qem6vAdkM4IUg3QDCIUKvrsth7P2GLwD1/B/LvObl/hj5s9+Vt8o3cqnTeI7cO1IgYid1ku8i9nw48uRoO8j8cj0Q="

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

install:
  - stack build --test --bench --only-dependencies

script:
  - stack test

jobs:
  include:
    - stage: Hackage deploy
      # n is for "store credentials" question
      script: echo -e "maksbotan\n${HACKAGE_PASSWORD}\nn" | stack upload --pvp-bounds both .
      on:
        tags: true
