sudo: false
language: generic

env:
  global:
      # HACKAGE_PASSWORD
    - secure: "OYj6b5xb1DxEMB3CHmjSN0p6cIYzI5xMhSeWm4BC2NKG8vx4PYkk3yrKBg3jBuYqC5I9TKN5xiqhENHqg3nULgL8/9swXGu/hg3I8P48yrErldMuVEBC0qPv7e1RS/rxacMXI5JIJEzgRYfYTVqkRuLrVvAilBM6GgLOL3+mVbVWJXt8PNK6gyAfE7CSNHWqHxc1GafDelxEBy75KRlcjNFk16AfmYdNyREiFsOfO5uBwFFKW/ETTbzuc9YHjEouBcl0N6MoQay8Gkpg6SPQkh/sXB1pFF6l9j3WlnqH5HCo3oN7DtvKQrG6xGwdKvl4gUwi4nOg38fvExDwJNXw1V/n1tc27GuX5hbiO5zagjPieCId58+2FmVsj8nlrSG0XycQISx/RTAslWW63QfVZVNIgAdUA29VyNEgJKJ32uOPHO++4kF5bLTMsCmbisaVJk4Hi0ASc3f2GFhSXvt/5THJ+Evtgo7YvNsKLafZDHQiGr/n1pkKNHidsa5iTnyXglvWRlIaToOGR+TQvDWVKLbXdBuTjpI7qPM4XuLliN7xE+J94NKH6ZAQznjceDo7TBaDsN0qdMeiQMlbyGHKNi2MAFkZ+RnXcuCApv51XLF2qUxPrIhE33Wz4tkJZlS6FV/D057YJiQVoSboBjaujnMZQrZSMBeJPOZrhI7PnDs="

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

install:
  - stack build --test --bench --only-dependencies

script:
  - stack test

jobs:
  include:
    - stage: Hackage deploy
      # n is for "store credentials" question
      script: echo -e "AlexKane\n${HACKAGE_PASSWORD}\nn" | stack upload --pvp-bounds both .
      on:
        tags: true
