sudo: false
language: generic

env:
  global:
      # HACKAGE_PASSWORD
    - secure: "gztlCckwVLGwu5a7zQUlg5S2YlE+V/d0WPVfdYlnbBTF1JLO8fbHaXBD86igr3505KiZzdhY7ik5JF49R60rEqeODgu9mW0SDTJy7gOYysyfJsd0ewWPM0y6rO2TJg3MSZD5Y9OzAkEsoWgejyokLg2sIPCtqImdjiy3+wG/DLwKGy7Mejl08r9fQkA4L+R+sIr0blGq5DLuIqp6LBYyzmB0MFJPoCrtFvvDVoAPyUGEsiVGJ5bLSa2sozM7vu4oFOvlQLVr/jm3IJ+6ljHQOSeW8VdEqB6hgEjy2XanSDRsktajSN+XkMbJilAnr/Aw3Vq8BPcItKLmy8KpSApAArqKLMRIEXN1lL3Fx2bJT9OBpWeqkX5E4oXkz6hPgCe80szPX2Q6aRH+SYztrNOnmcCAo5m/uPdorm0b5rwMssw8b84jlAti2Gj40Ik+WLBM98QEmWJ/5bHds2xio+y5BIVcEkVubmXi3DHFzVNVenfBp9mEPGxWPyCaPA7Zsafe1LZvKD0jDyl48k8p65LEQEICwcy3e+atl4OT4TaC0SsRBrC1TcqcaSYcOh1V2OywXGbNiM0fWVVrDIAxsV5gxYzyBQyaRdqt6XugsvexCxnQJ8B3kxbAbsvNLrTPKy0QfP23X5zTJ5ce9cyajeyRs9K0gJ3fLIE1EaqjqZBiiD0="

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

install:
  - stack build --test --bench --only-dependencies

script:
  - stack test

jobs:
  include:
    - stage: Hackage deploy
      # n is for "store credentials" question
      script: echo -e "AlexKane\n${HACKAGE_PASSWORD}\nn" | stack upload --pvp-bounds upper --pvp-bounds lower .
      on:
        tags: true
